version: "3.8"

services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    environment:
      DATABASE_URL: ${DATABASE_URL}         # יגיע מה-env file
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5000/api/hello || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on:
      backend:
        condition: service_healthy