# docker-compose.ci.yml
version: "3.8"

services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5000/api/hello || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 25

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on:
      backend:
        condition: service_healthy
    # בריאות לפרונט
    healthcheck:
      test: ["CMD-SHELL", "node -e \"http=require('http');http.get('http://localhost:3000',res=>process.exit(res.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 5s
      timeout: 3s
      retries: 25