name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Up
        run: |
          docker compose up -d --build
          echo "Waiting for containers to be ready..."
          sleep 15

      - name: Test backend API
        run: curl --fail http://localhost:5000/api/hello

      - name: Test frontend response
        run: curl --fail http://localhost:3000

      - name: Shutdown Docker Compose
        run: docker compose down